version: "3"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    networks:
      - default
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--global.sendAnonymousUsage=false"
      - "--certificatesresolvers.ssl.acme.httpchallenge=true"
      - "--certificatesresolvers.ssl.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.ssl.acme.email=${CERTIFICATE_EMAIL}"
      - "--certificatesresolvers.ssl.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  backend:
    restart: always
    container_name: "api-vizinhanca-shopping.com.br"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
    command: sh -c "yarn start:prod"
    image: dudurosa/vizinhanca-shopping
    volumes:
      - "./:/usr/src/app"
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      API_PORT: "${API_PORT}"
      API_URL: "${API_URL}"
      DATABASE_URL: "${DATABASE_URL}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      HASH_SALT: "${HASH_SALT}"
    labels:
      traefik.enable: true
      traefik.http.routers.backend1.service: backend
      traefik.http.routers.backend.rule: Host(`${API_HOST}`)
      traefik.http.routers.backend.entrypoints: http
      traefik.http.routers.backend-secure.rule: Host(`${API_HOST}`)
      traefik.http.routers.backend-secure.entrypoints: https
      traefik.http.routers.backend-secure.tls.certresolver: ssl
      traefik.http.services.backend.loadbalancer.server.port: ${API_PORT}

networks:
  default:
    driver: bridge
