import { promises as fs } from 'fs'
import { join, basename } from 'path'
import * as glob from 'glob'
import path from 'path'

const currentFilePath = __filename
const i18nDir = path.join(path.dirname(currentFilePath))
const outputDir = join(i18nDir, 'generated')
const outputFile = join(outputDir, 'i18n.types.ts')

async function generateTypes() {
  try {
    const files = glob.sync(`${i18nDir}/**/*.json`, {
      ignore: `${outputDir}/**`,
    })
    const translations: { [locale: string]: { [namespace: string]: any } } = {}

    for (const file of files) {
      const fileContent = await fs.readFile(file, 'utf-8')
      const jsonContent = JSON.parse(fileContent)
      const namespace = basename(file, '.json')
      const locale = file.split('/').slice(-2, -1)[0]

      if (!translations[locale]) {
        translations[locale] = {}
      }

      translations[locale][namespace] = jsonContent
    }

    if (Object.keys(translations).length === 0) {
      throw new Error('No translation files found')
    }

    const types = generateTypesFromTranslations(translations)
    await fs.mkdir(outputDir, { recursive: true })
    await fs.writeFile(outputFile, types)
  } catch (err) {
    console.error('Error generating types:', err)
    process.exit(1)
  }
}

function generateTypesFromTranslations(translations: {
  [locale: string]: { [namespace: string]: any }
}): string {
  const typeLines: string[] = []
  typeLines.push(`/* DO NOT EDIT, file generated by script */`)
  typeLines.push(``)
  typeLines.push(`/* eslint-disable */`)
  typeLines.push(`/* prettier-ignore */`)
  typeLines.push(`import { Path } from "nestjs-i18n";`)
  typeLines.push(`export type I18nTranslations = {`)

  const locales = Object.keys(translations)
  if (locales.length === 0) {
    throw new Error('No locales found in translations')
  }

  const keys = Object.keys(translations[locales[0]])
  if (keys.length === 0) {
    throw new Error('No namespaces found in translations')
  }

  for (const key of keys) {
    typeLines.push(generateNamespaceType(key, translations[locales[0]][key]))
  }

  typeLines.push(`};`)
  typeLines.push(`/* prettier-ignore */`)
  typeLines.push(`export type I18nPath = Path<I18nTranslations>;`)

  return typeLines.join('\n')
}

function generateNamespaceType(
  namespace: string,
  json: any,
  indentLevel = 1,
): string {
  const indent = '  '.repeat(indentLevel)
  const lines: string[] = []
  lines.push(`${indent}"${namespace}": {`)

  for (const [key, value] of Object.entries(json)) {
    if (typeof value === 'object' && value !== null) {
      lines.push(generateNamespaceType(key, value, indentLevel + 1))
    } else {
      lines.push(`${indent}  "${key}": string;`)
    }
  }

  lines.push(`${indent}};`)
  return lines.join('\n')
}

generateTypes().catch((err) => {
  console.error('Error generating types:', err)
  process.exit(1)
})
