export const defaultUsers = {
  admin: {
    email: 'admin@centerlight.com',
    password: 'ç1@adm1n',
    person: {
      name: 'Admin Seed',
      birthdate: '1990-01-01',
      document: '12345678900',
      stateId: 1,
      cityId: 1,
    },
  },
  manager: {
    email: 'gestor@centerlight.com',
    password: 'ç1@manager',
    person: {
      name: 'Manager Seed',
      birthdate: '1990-01-01',
      document: '12345678901',
      stateId: 1,
      cityId: 1,
    },
  },
  user: {
    email: 'user@centerlight.com',
    password: 'ç1@user',
    person: {
      name: 'User Seed',
      birthdate: '1990-01-01',
      document: '12345678902',
      stateId: 1,
      cityId: 1,
    },
  },
  pilot: {
    email: 'pilot@centerlight.com',
    password: 'ç1@pilot',
    person: {
      name: 'Pilot Seed',
      birthdate: '1990-01-01',
      document: '12345678903  ',
      isPilot: true,
      stateId: 1,
      cityId: 1,
    },
  },
}

export const brazilStates = [
  { name: 'Acre', code: 'AC' },
  { name: 'Alagoas', code: 'AL' },
  { name: 'Amazonas', code: 'AM' },
  { name: 'Amapá', code: 'AP' },
  { name: 'Bahia', code: 'BA' },
  { name: 'Ceará', code: 'CE' },
  { name: 'Distrito Federal', code: 'DF' },
  { name: 'Espírito Santo', code: 'ES' },
  { name: 'Goiás', code: 'GO' },
  { name: 'Maranhão', code: 'MA' },
  { name: 'Minas Gerais', code: 'MG' },
  { name: 'Mato Grosso do Sul', code: 'MS' },
  { name: 'Mato Grosso', code: 'MT' },
  { name: 'Pará', code: 'PA' },
  { name: 'Paraíba', code: 'PB' },
  { name: 'Pernambuco', code: 'PE' },
  { name: 'Piauí', code: 'PI' },
  { name: 'Paraná', code: 'PR' },
  { name: 'Rio de Janeiro', code: 'RJ' },
  { name: 'Rio Grande do Norte', code: 'RN' },
  { name: 'Rondônia', code: 'RO' },
  { name: 'Roraima', code: 'RR' },
  { name: 'Rio Grande do Sul', code: 'RS' },
  { name: 'Santa Catarina', code: 'SC' },
  { name: 'Sergipe', code: 'SE' },
  { name: 'São Paulo', code: 'SP' },
  { name: 'Tocantins', code: 'TO' },
]
